#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Running lints"
rye run lint

echo "==> Making sure it imports"
rye run python -c 'import studio_minus_sdk_minus_try_minus_to_minus_fix'

