name: Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: github.repository == 'clear-street/studio-sdk-python'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v3
        id: production-token
        with:
          client-id: ${{ secrets.STLC_CLIENT_ID_PROD }}
          private-key: ${{ secrets.STLC_CLIENT_PRIVATE_KEY_PROD }}
          owner: clear-street
          repositories: studio-sdk-python

      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
